### ISSUE TITLE
Calling `reset!` within `render` of app

### ISSUE THREAD

**Issue by kevinrobinson** [circleci/frontend#16]
Hi!  I apologize if this is the wrong place to bring this up, and am happy to move elsewhere.  This project is amazing, and I have much respect and gratitude for you all open sourcing it. :)

I noticed that in the `render` method of the `app` component, that there was a `reset!` to an atom that the component closes over.  I was curious about this, in trying to see how smart ClojureScript folks have added their own flavors and styles on top of React.  This is what I'm looking at: https://github.com/circleci/frontend/blob/master/src-cljs/frontend/components/app.cljs#L106  I'm not fully understanding why this needs to be reset, especially since it's reset to the same value each time.

**Comment by brandonbloom** [comment]
Assuming you mean https://github.com/circleci/frontend/blob/7497796b85ce380d03c480a0d4f2c5aba2fcdedc/src-cljs/frontend/components/app.cljs#L108-L109 (line numbers moved), then it's not reset to the same thing every time. Both of those functions close over `owner` which has object identity and so potentially changes on each render.
