### ISSUE TITLE
What sets renderContext.figwheelUrl?

### ISSUE THREAD

**Issue by Peeja** [circleci/frontend#19]
I'm having trouble getting Figwheel to run. It appears to be looking for a Figwheel URL in `(get-in @state [:render-context :figwheel_url])`, which is initialized from `window.renderContext.figwheelUrl`. But my `renderContext` doesn't have a `figwheelUrl`, and I don't see any code that would set one.

Am I missing a step? Or is there something missing in the code?

**Comment by brandonbloom** [comment]
This is an unfortunate consequence of the fact that the code which bootstraps the client-side application is not present in this code base. The actual HTML/JS/etc is served from our closed-source backend, but we'd like to move that bit of code to be open source as well. In the meantime, you can grep for `initial-query-map` to see how other settings allow overriding from the URL, or just manually hack in a manual value yourself. Sorry about the inconvenience!
