### ISSUE TITLE
Bitbucket support

### ISSUE THREAD

**Issue by nicodmf** [circleci/frontend#32]
Hello,

Really good solution that i use for a client which has github. 

All our repositories are on bitbucket, can we help to develop this functionnality ?

Best Regards,

Nicolas

**Comment by bellkev** [comment]
Hi @nicodmf this is a feature request that we have received before and is on our roadmap, though I can't provide any information on when we might add support. I'm going to go ahead and close this, since it is not specific to the frontend project.

**Comment by ZakTaccardi** [comment]
Is there a related feature that I can use to track this? Would love to use CircleCI, but currently using bitbucket...

**Comment by bellkev** [comment]
Hey @ZakTaccardi, this issue is now being tracked in our public discuss page: http://discuss.circleci.com/t/add-support-for-bitbucket/16 Please comment or upvote there!
