### ISSUE TITLE
What's your main editor?

### ISSUE THREAD

**Issue by huaoguo** [circleci/frontend#58]
I'm a clojure enthusiast, I'm learning it. I'm very glad to see a so famous project as circleci was written in clojurescript. My question is what the main source code editor are you using to edit clojurescript, Emacs or LightTable or other?

**Comment by Peeja** [comment]
Hi, @huaoguo!

Many of us at CircleCI use Emacs, and several of those people use [Spacemacs](https://github.com/syl20bnr/spacemacs). Others use Vim. I don't think anyone currently uses LightTable. I believe someone used to use Cursive, but doesn't anymore.

Personally, I can highly recommend Spacemacs. I run it in "holy mode", which turns off `evil-mode` (the Vim emulation). I also use [Lispy](https://github.com/abo-abo/lispy), which I love dearly for editing lisps. It has the ease of Vim keybindings without the mode switching of Vim.

**Comment by huaoguo** [comment]
@Peeja Thanks for your reply!
